import pandas as pd

#Generated by chat gpt

# Define the corpus data for flowers with thematic, question, and answer
data = {
    "Thematics": [
        "National Flowers", "Night Bloomers", "Love Symbols", "Fragrant Flowers",
        "Wedding Flowers", "Sun Lovers", "Remembrance Flowers", "Thousand Leaves",
        "Luxury Symbols", "Winter Bloomers", "Apology Flowers", "Greek Names",
        "Tea Flowers", "Cheerful Flowers", "Sacred Flowers", "Easter Flowers",
        "New Beginnings", "Sun Followers", "Greek Mythology", "Purple Flowers",
        "Valentine's Day", "South African Flowers", "Trumpet Flowers", "Rainbow Flowers",
        "Peaceful Flowers", "Dutch Named", "Heart-shaped Leaves", "Medicinal Flowers",
        "Teacher Appreciation", "Star Named", "Desert Flowers", "Hawaiian Leis",
        "Southern Symbols", "Delicate Petals", "Saffron Production", "Kyoto Symbol",
        "Friendship Symbols", "Round Blooms", "Eternal Life", "Christmas Flowers",
        "Blue Dyes", "Buddhist Symbols", "Latin Sword", "Mother's Day Bouquets",
        "Trumpet Shape", "Fall Season", "Resilient Flowers", "Culinary Flowers",
        "Humility Symbols", "Lily Named"
    ],
    "Questions": [
        "What is the national flower of Japan?",
        "Which flower is known as the 'Queen of the Night'?",
        "Which flower symbolizes love and passion?",
        "Which flower is famous for its beautiful fragrance and is often used in perfumes?",
        "What flower represents purity and is often used in weddings?",
        "Which flower is known as the 'Sun's Favorite'?",
        "Which flower is associated with the remembrance of the dead, particularly in Mexico?",
        "Which flower's name means 'a thousand leaves'?",
        "Which flower is considered a symbol of luxury and wealth in Chinese culture?",
        "Which flower is known for blooming in the harsh conditions of winter?",
        "Which flower is often given as a sign of apology?",
        "Which flower has a name that means 'beautiful' in Greek?",
        "Which flower is used to make a popular type of tea, especially in China?",
        "Which flower is known for its bright yellow color and is a symbol of cheerfulness?",
        "Which flower was sacred to the ancient Egyptians?",
        "Which flower is often associated with the Easter holiday?",
        "Which flower symbolizes new beginnings and rebirth?",
        "Which flower is known for its ability to open and close with the sun?",
        "Which flower is known as the 'Flower of the Gods' in Greek mythology?",
        "Which flower is famous for its various shades of purple and its pleasant scent?",
        "Which flower is often associated with the month of February and Valentine's Day?",
        "Which flower is native to South Africa and is known for its unique shape?",
        "Which flower is known for its large, trumpet-shaped blooms and vibrant colors?",
        "Which flower has a name derived from the Greek word for 'rainbow'?",
        "Which flower is a symbol of peace and calmness, often seen in blue and white?",
        "Which flower is named after a famous Dutch painter?",
        "Which flower is known for its heart-shaped leaves and blooms?",
        "Which flower is known for its medicinal properties and is often used in herbal teas?",
        "Which flower is often given to teachers to show appreciation?",
        "Which flower's name means 'star' in Greek?",
        "Which flower is known for its ability to thrive in dry, desert conditions?",
        "Which flower is often used in leis in Hawaii?",
        "Which flower is a traditional symbol of the American South?",
        "Which flower is known for its delicate petals and sweet fragrance?",
        "Which flower is often used in the production of saffron?",
        "Which flower is associated with the city of Kyoto, Japan?",
        "Which flower symbolizes friendship and happiness?",
        "Which flower is known for its large, round blooms and is often used in floral arrangements?",
        "Which flower is a symbol of eternal life and is often seen in ancient art?",
        "Which flower is known for its vibrant red color and is often associated with Christmas?",
        "Which flower is known for its striking blue color and is often used in dyes?",
        "Which flower is often associated with the Buddhist religion?",
        "Which flower's name means 'sword' in Latin?",
        "Which flower is often used in bouquets for Mother's Day?",
        "Which flower is known for its trumpet-like shape and vibrant yellow color?",
        "Which flower is often associated with the fall season?",
        "Which flower is known for its resilience and ability to survive harsh conditions?",
        "Which flower is famous for its use in culinary dishes, particularly in France?",
        "Which flower is often associated with the concept of humility?",
        "Which flower's name means 'flower of the lily' in Latin?"
    ],
    "Answers": [
        "Cherry Blossom", "Cereus", "Rose", "Jasmine", "Lily", "Sunflower", "Marigold", "Yarrow",
        "Peony", "Camellia", "Orchid", "Calla Lily", "Chrysanthemum", "Daffodil", "Lotus", "Lily",
        "Daffodil", "Sunflower", "Carnation", "Lavender", "Rose", "Protea", "Hibiscus", "Iris",
        "White Poppy", "Tulip", "Bleeding Heart", "Chamomile", "Apple Blossom", "Aster",
        "Cactus Flower", "Plumeria", "Magnolia", "Gardenia", "Saffron Crocus", "Cherry Blossom",
        "Yellow Rose", "Hydrangea", "Ivy", "Poinsettia", "Bluebell", "Lotus", "Gladiolus", "Carnation",
        "Daffodil", "Chrysanthemum", "Dandelion", "Lavender", "Violet", "Lilium"
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Function to rewrite the answer with specific context
def rewrite_answer_with_specific_context(row):
    question = row['Questions']
    answer = row['Answers']
    if "national flower" in question.lower():
        return f"The national flower of Japan is {answer}."
    elif "queen of the night" in question.lower():
        return f"The flower known as the 'Queen of the Night' is {answer}."
    elif "symbolizes love and passion" in question.lower():
        return f"The flower that symbolizes love and passion is {answer}."
    elif "beautiful fragrance" in question.lower():
        return f"The flower famous for its beautiful fragrance and often used in perfumes is {answer}."
    elif "represents purity" in question.lower():
        return f"The flower that represents purity and is often used in weddings is {answer}."
    elif "sun's favorite" in question.lower():
        return f"The flower known as the 'Sun's Favorite' is {answer}."
    elif "remembrance of the dead" in question.lower():
        return f"The flower associated with the remembrance of the dead, particularly in Mexico, is {answer}."
    elif "a thousand leaves" in question.lower():
        return f"The flower whose name means 'a thousand leaves' is {answer}."
    elif "symbol of luxury and wealth" in question.lower():
        return f"The flower considered a symbol of luxury and wealth in Chinese culture is {answer}."
    elif "harsh conditions of winter" in question.lower():
        return f"The flower known for blooming in the harsh conditions of winter is {answer}."
    elif "sign of apology" in question.lower():
        return f"The flower often given as a sign of apology is {answer}."
    elif "name that means 'beautiful'" in question.lower():
        return f"The flower with a name that means 'beautiful' in Greek is {answer}."
    elif "make a popular type of tea" in question.lower():
        return f"The flower used to make a popular type of tea, especially in China, is {answer}."
    elif "bright yellow color" in question.lower():
        return f"The flower known for its bright yellow color and is a symbol of cheerfulness is {answer}."
    elif "sacred to the ancient Egyptians" in question.lower():
        return f"The flower that was sacred to the ancient Egyptians is {answer}."
    elif "easter holiday" in question.lower():
        return f"The flower often associated with the Easter holiday is {answer}."
    elif "symbolizes new beginnings" in question.lower():
        return f"The flower that symbolizes new beginnings and rebirth is {answer}."
    elif "open and close with the sun" in question.lower():
        return f"The flower known for its ability to open and close with the sun is {answer}."
    elif "flower of the gods" in question.lower():
        return f"The flower known as the 'Flower of the Gods' in Greek mythology is {answer}."
    elif "shades of purple" in question.lower():
        return f"The flower famous for its various shades of purple and its pleasant scent is {answer}."
    elif "valentine's day" in question.lower():
        return f"The flower often associated with the month of February and Valentine's Day is {answer}."
    elif "native to South Africa" in question.lower():
        return f"The flower native to South Africa and known for its unique shape is {answer}."
    elif "large, trumpet-shaped blooms" in question.lower():
        return f"The flower known for its large, trumpet-shaped blooms and vibrant colors is {answer}."
    elif "name derived from the Greek word for 'rainbow'" in question.lower():
        return f"The flower with a name derived from the Greek word for 'rainbow' is {answer}."
    elif "symbol of peace and calmness" in question.lower():
        return f"The flower that is a symbol of peace and calmness, often seen in blue and white, is {answer}."
    elif "named after a famous Dutch painter" in question.lower():
        return f"The flower named after a famous Dutch painter is {answer}."
    elif "heart-shaped leaves and blooms" in question.lower():
        return f"The flower known for its heart-shaped leaves and blooms is {answer}."
    elif "medicinal properties" in question.lower():
        return f"The flower known for its medicinal properties and is often used in herbal teas is {answer}."
    elif "given to teachers to show appreciation" in question.lower():
        return f"The flower often given to teachers to show appreciation is {answer}."
    elif "name means 'star'" in question.lower():
        return f"The flower whose name means 'star' in Greek is {answer}."
    elif "thrive in dry, desert conditions" in question.lower():
        return f"The flower known for its ability to thrive in dry, desert conditions is {answer}."
    elif "used in leis in Hawaii" in question.lower():
        return f"The flower often used in leis in Hawaii is {answer}."
    elif "symbol of the American South" in question.lower():
        return f"The flower that is a traditional symbol of the American South is {answer}."
    elif "delicate petals and sweet fragrance" in question.lower():
        return f"The flower known for its delicate petals and sweet fragrance is {answer}."
    elif "production of saffron" in question.lower():
        return f"The flower often used in the production of saffron is {answer}."
    elif "associated with the city of Kyoto, Japan" in question.lower():
        return f"The flower associated with the city of Kyoto, Japan, is {answer}."
    elif "symbolizes friendship and happiness" in question.lower():
        return f"The flower that symbolizes friendship and happiness is {answer}."
    elif "large, round blooms" in question.lower():
        return f"The flower known for its large, round blooms and is often used in floral arrangements is {answer}."
    elif "symbol of eternal life" in question.lower():
        return f"The flower that is a symbol of eternal life and is often seen in ancient art is {answer}."
    elif "vibrant red color and is often associated with Christmas" in question.lower():
        return f"The flower known for its vibrant red color and is often associated with Christmas is {answer}."
    elif "striking blue color and is often used in dyes" in question.lower():
        return f"The flower known for its striking blue color and is often used in dyes is {answer}."
    elif "associated with the Buddhist religion" in question.lower():
        return f"The flower often associated with the Buddhist religion is {answer}."
    elif "name means 'sword' in Latin" in question.lower():
        return f"The flower whose name means 'sword' in Latin is {answer}."
    elif "bouquets for Mother's Day" in question.lower():
        return f"The flower often used in bouquets for Mother's Day is {answer}."
    elif "trumpet-like shape and vibrant yellow color" in question.lower():
        return f"The flower known for its trumpet-like shape and vibrant yellow color is {answer}."
    elif "associated with the fall season" in question.lower():
        return f"The flower often associated with the fall season is {answer}."
    elif "resilience and ability to survive harsh conditions" in question.lower():
        return f"The flower known for its resilience and ability to survive harsh conditions is {answer}."
    elif "use in culinary dishes, particularly in France" in question.lower():
        return f"The flower famous for its use in culinary dishes, particularly in France, is {answer}."
    elif "associated with the concept of humility" in question.lower():
        return f"The flower often associated with the concept of humility is {answer}."
    elif "name means 'flower of the lily' in Latin" in question.lower():
        return f"The flower whose name means 'flower of the lily' in Latin is {answer}."
    else:
        return answer

# Apply the function to the DataFrame
df["Answers"] = df.apply(rewrite_answer_with_specific_context, axis=1)

# Save the DataFrame to a CSV file
csv_path = "../corpus/data.csv"
df.to_csv(csv_path, index=False)
